### ISSUE TITLE
A little Review/Questions/Suggestion etc

### ISSUE THREAD

**Issue by evnix** [zuixjs/zuix#6]
What I really liked about zuix:

````
<script src="https://genielabs.github.io/zuix/js/zuix.min.js"></script>

````
I love this!!
I don't know what is wrong with everyone else, why do i need npm, and a ton load of npm commands and a gazillion dependencies just to run your javascript library.

Please keep it this way.

I love the following:
````
<div data-ui-include="https://genielabs.github.io/zuix/site/common/links"></div>
````
but can I have pages without `.html` for example `/api/v1/generateContent/100/200` ?

-----------------

is this possible:
````
<div  data-ui-include="{someVariable}"></div>
````
and then use something like an onclick

````
onClickHandler(){
  someVariable = "/api/v1/etc/etc";
}
````

I imagine with the help of lazy loading, it would be really easy to create a wiki or documentation without using crazy things like static site generators. This would be a killer static website making framework!! If it is already possible, may be some example would be nice. I know about the Hacker News thing. But would love a much more bare bones stripped down version.

So far, I liked the framework because it does makes things simpler!!! Thanks for this!!

**Comment by genemars** [comment]
> but can I have pages without .html for example /api/v1/generateContent/100/200 ?

Yes by using the **cext** parameter in the loading options. This parameter allow you set a custom extension that in your case will be just empty string ''.

Full options list is described here: https://genielabs.github.io/zuix/#/api#ZUIX_API--ContextOptions .

**Example**
```js
var my_options = {
    cext: ''
}
```

```html
<div data-ui-include="path/to/content" data-ui-options="my_options"></div>
```

And yes you can definitely create static sites without need of going through a server side generation process nor by using external tools.
As an example please have a look at this pure client-side javascript content generation supporting markdown as well (i.e. like Jekyll):

https://github.com/genielabs/HomeGenie/tree/gh-pages

which is published at:
https://genielabs.github.io/HomeGenie/

Perhaps I'll publish a boiler plate for such kind of sites. I've just got too much stuff in my head right now :D that I don't know what do do first. I wish more people would get involved in this project and contribute.

Thank you for liking this. :)

**Comment by piyushpatel2005** [comment]
I'm not sure whether I am posting in the right section. I liked Zuix.js from the initial look. I am not a professional developer though I would love the idea of having single file creating superb Modular application. I'm not sure whether it is my browser problem, but Github docs page didn't load in Chrome and Safari on my iPad as well as iPhone. I was trying to just go through the API to see what is posssible with Zuix.

Additionally, I would like this to be one of the popular frameworks. Probably you need little time and effort to market this one. Just my view!

Love it!

**Comment by genemars** [comment]
So it's been a while and there have been lot of progress.
Have a look to the new website 
https://genielabs.github.io/zuix

**Comment by evnix** [comment]
That's some nice work!!!
